/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevo_clon;
import Ventanas.Informacion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.awt.image.BufferedImage;
import tabla.Elemento;
import tabla.Tabla_Periodica;

/**
 *
 * @author XPC
 */
public class nueva_Tabla extends javax.swing.JFrame {
    
    public nueva_Tabla() throws IOException {
        super();
        initComponents();
        Tabla_Periodica tabla = new Tabla_Periodica();
        Elemento []elementos = tabla.getElementos();
        Boton1.setText(elementos[0].getSimbolo());
        Boton2.setText(elementos[1].getSimbolo());
        Boton3.setText(elementos[2].getSimbolo());
        Boton4.setText(elementos[3].getSimbolo());
        Boton5.setText(elementos[4].getSimbolo());
        Boton6.setText(elementos[5].getSimbolo());
        Boton7.setText(elementos[6].getSimbolo());
        Boton8.setText(elementos[7].getSimbolo());
        Boton9.setText(elementos[8].getSimbolo());
        Boton10.setText(elementos[9].getSimbolo());
        Boton11.setText(elementos[10].getSimbolo());
        Boton12.setText(elementos[11].getSimbolo());
        Boton13.setText(elementos[12].getSimbolo());
        Boton14.setText(elementos[13].getSimbolo());
        Boton15.setText(elementos[14].getSimbolo());
        Boton16.setText(elementos[15].getSimbolo());
        Boton17.setText(elementos[16].getSimbolo());
        Boton18.setText(elementos[17].getSimbolo());
        Boton19.setText(elementos[18].getSimbolo());
        Boton20.setText(elementos[19].getSimbolo());
        Boton21.setText(elementos[20].getSimbolo());
        Boton22.setText(elementos[21].getSimbolo());
        Boton23.setText(elementos[22].getSimbolo());
        Boton24.setText(elementos[23].getSimbolo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Boton1 = new javax.swing.JButton();
    Boton3 = new javax.swing.JButton();
    Boton9 = new javax.swing.JButton();
    Boton6 = new javax.swing.JButton();
    Boton22 = new javax.swing.JButton();
    wqqw = new javax.swing.JButton();
    ewwq = new javax.swing.JButton();
    Boton10 = new javax.swing.JButton();
    Boton7 = new javax.swing.JButton();
    Boton23 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    Boton11 = new javax.swing.JButton();
    Boton24 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();
    Boton12 = new javax.swing.JButton();
    Boton25 = new javax.swing.JButton();
    jButton23 = new javax.swing.JButton();
    jButton24 = new javax.swing.JButton();
    Boton13 = new javax.swing.JButton();
    Boton26 = new javax.swing.JButton();
    jButton27 = new javax.swing.JButton();
    jButton28 = new javax.swing.JButton();
    Boton14 = new javax.swing.JButton();
    jButton30 = new javax.swing.JButton();
    jButton31 = new javax.swing.JButton();
    jButton32 = new javax.swing.JButton();
    Boton15 = new javax.swing.JButton();
    jButton34 = new javax.swing.JButton();
    jButton35 = new javax.swing.JButton();
    jButton36 = new javax.swing.JButton();
    Boton16 = new javax.swing.JButton();
    jButton38 = new javax.swing.JButton();
    jButton39 = new javax.swing.JButton();
    jButton40 = new javax.swing.JButton();
    Boton17 = new javax.swing.JButton();
    jButton42 = new javax.swing.JButton();
    jButton43 = new javax.swing.JButton();
    jButton44 = new javax.swing.JButton();
    Boton18 = new javax.swing.JButton();
    jButton46 = new javax.swing.JButton();
    jButton47 = new javax.swing.JButton();
    jButton48 = new javax.swing.JButton();
    Boton19 = new javax.swing.JButton();
    jButton50 = new javax.swing.JButton();
    jButton51 = new javax.swing.JButton();
    jButton52 = new javax.swing.JButton();
    Boton20 = new javax.swing.JButton();
    jButton54 = new javax.swing.JButton();
    jButton55 = new javax.swing.JButton();
    jButton56 = new javax.swing.JButton();
    Boton5 = new javax.swing.JButton();
    Boton21 = new javax.swing.JButton();
    Boton8 = new javax.swing.JButton();
    jButton59 = new javax.swing.JButton();
    jButton60 = new javax.swing.JButton();
    jButton61 = new javax.swing.JButton();
    jButton68 = new javax.swing.JButton();
    jButton69 = new javax.swing.JButton();
    jButton70 = new javax.swing.JButton();
    jButton71 = new javax.swing.JButton();
    jButton72 = new javax.swing.JButton();
    jButton73 = new javax.swing.JButton();
    jButton74 = new javax.swing.JButton();
    jButton75 = new javax.swing.JButton();
    jButton76 = new javax.swing.JButton();
    jButton77 = new javax.swing.JButton();
    jButton78 = new javax.swing.JButton();
    jButton79 = new javax.swing.JButton();
    jButton62 = new javax.swing.JButton();
    jButton63 = new javax.swing.JButton();
    jButton64 = new javax.swing.JButton();
    jButton65 = new javax.swing.JButton();
    jButton66 = new javax.swing.JButton();
    jButton67 = new javax.swing.JButton();
    jButton80 = new javax.swing.JButton();
    jButton81 = new javax.swing.JButton();
    jButton82 = new javax.swing.JButton();
    jButton83 = new javax.swing.JButton();
    jButton84 = new javax.swing.JButton();
    jButton85 = new javax.swing.JButton();
    Boton2 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton86 = new javax.swing.JButton();
    jButton87 = new javax.swing.JButton();
    jButton88 = new javax.swing.JButton();
    jButton89 = new javax.swing.JButton();
    jButton90 = new javax.swing.JButton();
    jButton97 = new javax.swing.JButton();
    jButton98 = new javax.swing.JButton();
    jButton99 = new javax.swing.JButton();
    jButton100 = new javax.swing.JButton();
    jButton101 = new javax.swing.JButton();
    jButton102 = new javax.swing.JButton();
    jButton103 = new javax.swing.JButton();
    jButton104 = new javax.swing.JButton();
    jButton105 = new javax.swing.JButton();
    jButton106 = new javax.swing.JButton();
    jButton107 = new javax.swing.JButton();
    jButton108 = new javax.swing.JButton();
    jButton109 = new javax.swing.JButton();
    jButton110 = new javax.swing.JButton();
    salir = new javax.swing.JButton();
    jButton111 = new javax.swing.JButton();
    jButton112 = new javax.swing.JButton();
    jButton113 = new javax.swing.JButton();
    jButton114 = new javax.swing.JButton();
    jButton115 = new javax.swing.JButton();
    jButton116 = new javax.swing.JButton();
    titulo = new javax.swing.JLabel();
    Boton4 = new javax.swing.JButton();
    fondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Boton1.setForeground(new java.awt.Color(255, 255, 255));
    Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCorrectas/AtomoHidrogeno.gif"))); // NOI18N
    Boton1.setText("H");
    Boton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton1ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, 70));

    Boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCorrectas/lithium.gif"))); // NOI18N
    Boton3.setText("A");
    Boton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton3ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 70, 60));

    Boton9.setText("A");
    Boton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton9ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 70, 50));

    Boton6.setText("A");
    getContentPane().add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 70, 50));

    Boton22.setText("A");
    Boton22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton22ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 70, 50));

    wqqw.setText("A");
    getContentPane().add(wqqw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 70, 50));

    ewwq.setText("A");
    getContentPane().add(ewwq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 70, 50));

    Boton10.setText("A");
    getContentPane().add(Boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, 50));

    Boton7.setText("A");
    getContentPane().add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 50));

    Boton23.setText("A");
    Boton23.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton23ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 70, 50));

    jButton14.setText("A");
    getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 70, 50));

    jButton15.setText("A");
    getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 70, 50));

    Boton11.setText("A");
    getContentPane().add(Boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 70, 50));

    Boton24.setText("A");
    Boton24.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton24ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 50));

    jButton20.setText("A");
    getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 70, 50));

    jButton21.setText("A");
    getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 70, 50));

    Boton12.setText("A");
    Boton12.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton12ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 70, 50));

    Boton25.setText("A");
    Boton25.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton25ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 70, 50));

    jButton23.setText("A");
    getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 70, 50));

    jButton24.setText("A");
    getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 70, 50));

    Boton13.setText("A");
    getContentPane().add(Boton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 70, 50));

    Boton26.setText("A");
    Boton26.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton26ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 70, 50));

    jButton27.setText("A");
    getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 70, 50));

    jButton28.setText("A");
    getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 70, 50));

    Boton14.setText("A");
    getContentPane().add(Boton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 70, 50));

    jButton30.setText("A");
    jButton30.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton30ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 70, 50));

    jButton31.setText("A");
    getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 70, 50));

    jButton32.setText("A");
    getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 70, 50));

    Boton15.setText("A");
    getContentPane().add(Boton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 70, 50));

    jButton34.setText("A");
    jButton34.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton34ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 70, 50));

    jButton35.setText("A");
    getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 70, 50));

    jButton36.setText("A");
    getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 70, 50));

    Boton16.setText("A");
    Boton16.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton16ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 70, 50));

    jButton38.setText("A");
    jButton38.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton38ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 70, 50));

    jButton39.setText("A");
    getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 70, 50));

    jButton40.setText("A");
    getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 70, 50));

    Boton17.setText("A");
    getContentPane().add(Boton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 70, 50));

    jButton42.setText("A");
    jButton42.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton42ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 70, 50));

    jButton43.setText("A");
    getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 70, 50));

    jButton44.setText("A");
    getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 70, 50));

    Boton18.setText("A");
    getContentPane().add(Boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, 70, 50));

    jButton46.setText("A");
    jButton46.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton46ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 70, 50));

    jButton47.setText("A");
    getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 70, 50));

    jButton48.setText("A");
    getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 70, 50));

    Boton19.setText("A");
    getContentPane().add(Boton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 70, 50));

    jButton50.setText("A");
    jButton50.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton50ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 70, 50));

    jButton51.setText("A");
    getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 70, 50));

    jButton52.setText("A");
    getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 70, 50));

    Boton20.setText("A");
    Boton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton20ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, 70, 50));

    jButton54.setText("A");
    jButton54.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton54ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 420, 70, 50));

    jButton55.setText("A");
    getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, 70, 50));

    jButton56.setText("A");
    getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 70, 50));

    Boton5.setText("A");
    getContentPane().add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 70, 50));

    Boton21.setText("A");
    getContentPane().add(Boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 360, 70, 50));

    Boton8.setText("A");
    getContentPane().add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 300, 70, 50));

    jButton59.setText("A");
    jButton59.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton59ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 420, 70, 50));

    jButton60.setText("A");
    getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 480, 70, 50));

    jButton61.setText("A");
    getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 550, 70, 50));

    jButton68.setText("A");
    getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 240, 70, 50));

    jButton69.setText("A");
    getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 360, 70, 50));

    jButton70.setText("A");
    getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 300, 70, 50));

    jButton71.setText("A");
    jButton71.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton71ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 420, 70, 50));

    jButton72.setText("A");
    getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 480, 70, 50));

    jButton73.setText("A");
    getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 550, 70, 50));

    jButton74.setText("A");
    getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 70, 50));

    jButton75.setText("A");
    getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 360, 70, 50));

    jButton76.setText("A");
    getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 300, 70, 50));

    jButton77.setText("A");
    jButton77.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton77ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 420, 70, 50));

    jButton78.setText("A");
    getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 480, 70, 50));

    jButton79.setText("A");
    getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 550, 70, 50));

    jButton62.setText("A");
    getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 240, 70, 50));

    jButton63.setText("A");
    getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 360, 70, 50));

    jButton64.setText("A");
    getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 300, 70, 50));

    jButton65.setText("A");
    jButton65.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton65ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 420, 70, 50));

    jButton66.setText("A");
    getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 480, 70, 50));

    jButton67.setText("A");
    getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 550, 70, 50));

    jButton80.setText("A");
    getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 240, 70, 50));

    jButton81.setText("A");
    getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 360, 70, 50));

    jButton82.setText("A");
    getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 300, 70, 50));

    jButton83.setText("A");
    jButton83.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton83ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 420, 70, 50));

    jButton84.setText("A");
    getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 480, 70, 50));

    jButton85.setText("A");
    getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 550, 70, 50));

    Boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.gif"))); // NOI18N
    Boton2.setText("H");
    Boton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton2ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 170, 80, 60));

    jButton9.setText("A");
    getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 240, 70, 50));

    jButton86.setText("A");
    getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 360, 70, 50));

    jButton87.setText("A");
    getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 300, 70, 50));

    jButton88.setText("A");
    jButton88.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton88ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 420, 70, 50));

    jButton89.setText("A");
    getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 480, 70, 50));

    jButton90.setText("A");
    getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 550, 70, 50));

    jButton97.setText("A");
    getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 70, 50));

    jButton98.setText("A");
    getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 70, 50));

    jButton99.setText("A");
    getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 70, 50));

    jButton100.setText("A");
    getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 710, 70, 50));

    jButton101.setText("A");
    getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 70, 50));

    jButton102.setText("A");
    getContentPane().add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 710, 70, 50));

    jButton103.setText("A");
    getContentPane().add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 70, 50));

    jButton104.setText("A");
    getContentPane().add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 710, 70, 50));

    jButton105.setText("A");
    getContentPane().add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 70, 50));

    jButton106.setText("A");
    getContentPane().add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 710, 70, 50));

    jButton107.setText("A");
    getContentPane().add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 70, 50));

    jButton108.setText("A");
    getContentPane().add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 710, 70, 50));

    jButton109.setText("A");
    getContentPane().add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 70, 50));

    jButton110.setText("A");
    getContentPane().add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 710, 70, 50));

    salir.setBackground(new java.awt.Color(0, 0, 102));
    salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    salir.setForeground(new java.awt.Color(255, 255, 255));
    salir.setText("Salir");
    salir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        salirActionPerformed(evt);
      }
    });
    getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 865, 70, 30));

    jButton111.setText("A");
    getContentPane().add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, 70, 50));

    jButton112.setText("A");
    getContentPane().add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 710, 70, 50));

    jButton113.setText("A");
    getContentPane().add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, 70, 50));

    jButton114.setText("A");
    getContentPane().add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 710, 70, 50));

    jButton115.setText("A");
    getContentPane().add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 640, 70, 50));

    jButton116.setText("A");
    getContentPane().add(jButton116, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 710, 70, 50));

    titulo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
    titulo.setForeground(new java.awt.Color(255, 255, 255));
    titulo.setText("Tabla Periodica");
    getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    Boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCorrectas/Berilyum.gif"))); // NOI18N
    Boton4.setText("A");
    Boton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Boton4ActionPerformed(evt);
      }
    });
    getContentPane().add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 70, 60));

    fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/planet.jpg"))); // NOI18N
    getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 925));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void Boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton22ActionPerformed

    private void Boton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton23ActionPerformed

    private void Boton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton24ActionPerformed

    private void Boton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton25ActionPerformed

    private void Boton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton26ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton88ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        Tabla_Periodica tabla = new Tabla_Periodica();
        Informacion ventana;
        ventana = new Informacion(2);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        Tabla_Periodica tabla = new Tabla_Periodica();
        Informacion ventana;
        ventana = new Informacion(3);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton12ActionPerformed

    private void Boton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton16ActionPerformed

    private void Boton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton20ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        Tabla_Periodica tabla = new Tabla_Periodica();
        Informacion ventana;
        ventana = new Informacion(0);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        Tabla_Periodica tabla = new Tabla_Periodica();
        Informacion ventana;
        ventana = new Informacion(1);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nueva_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nueva_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nueva_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nueva_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new nueva_Tabla().setVisible(true);
                } catch (IOException ex) {
                    //Logger.getLogger(nueva_Tabla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Boton1;
  private javax.swing.JButton Boton10;
  private javax.swing.JButton Boton11;
  private javax.swing.JButton Boton12;
  private javax.swing.JButton Boton13;
  private javax.swing.JButton Boton14;
  private javax.swing.JButton Boton15;
  private javax.swing.JButton Boton16;
  private javax.swing.JButton Boton17;
  private javax.swing.JButton Boton18;
  private javax.swing.JButton Boton19;
  private javax.swing.JButton Boton2;
  private javax.swing.JButton Boton20;
  private javax.swing.JButton Boton21;
  private javax.swing.JButton Boton22;
  private javax.swing.JButton Boton23;
  private javax.swing.JButton Boton24;
  private javax.swing.JButton Boton25;
  private javax.swing.JButton Boton26;
  private javax.swing.JButton Boton3;
  private javax.swing.JButton Boton4;
  private javax.swing.JButton Boton5;
  private javax.swing.JButton Boton6;
  private javax.swing.JButton Boton7;
  private javax.swing.JButton Boton8;
  private javax.swing.JButton Boton9;
  private javax.swing.JButton ewwq;
  private javax.swing.JLabel fondo;
  private javax.swing.JButton jButton100;
  private javax.swing.JButton jButton101;
  private javax.swing.JButton jButton102;
  private javax.swing.JButton jButton103;
  private javax.swing.JButton jButton104;
  private javax.swing.JButton jButton105;
  private javax.swing.JButton jButton106;
  private javax.swing.JButton jButton107;
  private javax.swing.JButton jButton108;
  private javax.swing.JButton jButton109;
  private javax.swing.JButton jButton110;
  private javax.swing.JButton jButton111;
  private javax.swing.JButton jButton112;
  private javax.swing.JButton jButton113;
  private javax.swing.JButton jButton114;
  private javax.swing.JButton jButton115;
  private javax.swing.JButton jButton116;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton23;
  private javax.swing.JButton jButton24;
  private javax.swing.JButton jButton27;
  private javax.swing.JButton jButton28;
  private javax.swing.JButton jButton30;
  private javax.swing.JButton jButton31;
  private javax.swing.JButton jButton32;
  private javax.swing.JButton jButton34;
  private javax.swing.JButton jButton35;
  private javax.swing.JButton jButton36;
  private javax.swing.JButton jButton38;
  private javax.swing.JButton jButton39;
  private javax.swing.JButton jButton40;
  private javax.swing.JButton jButton42;
  private javax.swing.JButton jButton43;
  private javax.swing.JButton jButton44;
  private javax.swing.JButton jButton46;
  private javax.swing.JButton jButton47;
  private javax.swing.JButton jButton48;
  private javax.swing.JButton jButton50;
  private javax.swing.JButton jButton51;
  private javax.swing.JButton jButton52;
  private javax.swing.JButton jButton54;
  private javax.swing.JButton jButton55;
  private javax.swing.JButton jButton56;
  private javax.swing.JButton jButton59;
  private javax.swing.JButton jButton60;
  private javax.swing.JButton jButton61;
  private javax.swing.JButton jButton62;
  private javax.swing.JButton jButton63;
  private javax.swing.JButton jButton64;
  private javax.swing.JButton jButton65;
  private javax.swing.JButton jButton66;
  private javax.swing.JButton jButton67;
  private javax.swing.JButton jButton68;
  private javax.swing.JButton jButton69;
  private javax.swing.JButton jButton70;
  private javax.swing.JButton jButton71;
  private javax.swing.JButton jButton72;
  private javax.swing.JButton jButton73;
  private javax.swing.JButton jButton74;
  private javax.swing.JButton jButton75;
  private javax.swing.JButton jButton76;
  private javax.swing.JButton jButton77;
  private javax.swing.JButton jButton78;
  private javax.swing.JButton jButton79;
  private javax.swing.JButton jButton80;
  private javax.swing.JButton jButton81;
  private javax.swing.JButton jButton82;
  private javax.swing.JButton jButton83;
  private javax.swing.JButton jButton84;
  private javax.swing.JButton jButton85;
  private javax.swing.JButton jButton86;
  private javax.swing.JButton jButton87;
  private javax.swing.JButton jButton88;
  private javax.swing.JButton jButton89;
  private javax.swing.JButton jButton9;
  private javax.swing.JButton jButton90;
  private javax.swing.JButton jButton97;
  private javax.swing.JButton jButton98;
  private javax.swing.JButton jButton99;
  private javax.swing.JButton salir;
  private javax.swing.JLabel titulo;
  private javax.swing.JButton wqqw;
  // End of variables declaration//GEN-END:variables
}
